parse_question:
  description: >
    Given question {question_text}, determine whether question is TABULAR or NON_TABULAR
  expected_output: >
    Given queston {question_text}, determine whether it is a tabular question 
    and return token TABULAR_QUESTION if question is tabular otherwise return NON_TABULAR_QUESTION token
  agent: question_parser_agent

generate_answer:
  description: >
    Generate precise response for a question by reading table data provided as part of the {question_text}
  expected_output: >
    Given question {question_text},  Generate precise response for a table data based question
  agent: answer_generator_agent

#extract_text_from_image:
#  agent: image_text_extractor
#  description: >
#    Extract text from the provided {image_file}. Ensure that the extracted text is accurate and complete,
#    and ready for any further analysis or processing tasks. The image file provided may contain
#    various text elements, so it's crucial to capture all readable text.
#  expected_output: >
#    A string containing the full text extracted from the image.
  
